#----------------------------- StartUp ----------------------------#
[[tasks]]
type = "StartUp"
params = { client_type = "YoStarEN", start_game_enabled = true }


#------------------------------ Fight -----------------------------#

[[tasks]]
type = "Fight"

[tasks.params]
expiring_medicine = 1000

# On any side story open, fight given side story stage
[[tasks.variants]]
condition = { type = "OnSideStory", client = "YoStarEN" }
params = { stage = "HS-9", series = 0 }

# Otherwise, fight PR-A-2 on Monday, PR-B-2 on Tuesday, PR-D-2 on Wednesday,
# PR-C-1 on Thursday, 1-7 for the rest of the week
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Mon"], timezone = "YoStarEN" }
params = { stage = "PR-A-2", series = 2 }
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Tue"], timezone = "YoStarEN" }
params = { stage = "PR-B-2", series = 2 }
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Wed"], timezone = "YoStarEN" }
params = { stage = "PR-D-2", series = 2 }
[[tasks.variants]]
condition = { type = "Weekday", weekdays = ["Thu"], timezone = "YoStarEN" }
params = { stage = "PR-C-2", series = 2 }
[[tasks.variants]]
params = { stage = "1-7", series = 6 }


#------------------------------ Mall ------------------------------#
[[tasks]]
type = "Mall"

[tasks.params]
shopping = false

[[tasks.variants]]
condition = { type = "Time", start = "18:00:00", end = "21:00:00" }
params = { credit_fight = true, select_formation = 4 }


#----------------------------- Infrast ----------------------------#
[[tasks]]
type = "Infrast"

[tasks.params]
mode = 10000
facility = ["Trade", "Reception", "Mfg", "Control", "Power", "Office", "Dorm"]
dorm_trust_enabled = false
filename = "242_4Gold.json"

[[tasks.variants]]
condition = { type = "Time", start = "19:00:00", end = "03:00:00" }
params = { plan_index = 2 }

[[tasks.variants]]
condition = { type = "Time", end = "11:00:00" }
params = { plan_index = 0 }

[[tasks.variants]]
condition = { type = "Time", start = "11:00:00" }
params = { plan_index = 1 }


#----------------------------- Recruit ----------------------------#
[[tasks]]
type = "Recruit"

[tasks.params]
refresh = true
times = 4
select = [4, 5]
confirm = [3, 4, 5]
skip_robot = false
recruitment_time = { '3' = 460 }


#------------------------------ Award -----------------------------#
[[tasks]]
type = "Award"

[tasks.params]
award = true
mail = true
orundum = true
specialaccess = true
