[connection]
preset = "MuMuPro"

[resource]
global_resource = "YoStarEN"
user_resource = false

[static_options]
cpu_ocr = false
gpu_ocr = 1

[instance_options]
touch_mode = "MaaTouch"
deployment_with_pause = false
adb_lite_enabled = false
kill_adb_on_exit = false
