[connection]
preset = "MuMuPro"
address = "127.0.0.1:5555"
adb_path = "/Applications/MuMuPlayer\\ Pro.app/Contents/MacOS/MuMu\\ Android\\ Device.app/Contents/MacOS/tools/adb"

[resource]
global_resource = "YoStarEN"
user_resource = false

[static_options]
cpu_ocr = false
gpu_ocr = 1

[instance_options]
touch_mode = "MaaTouch"
deployment_with_pause = false
adb_lite_enabled = false
kill_adb_on_exit = false
